---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c)
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

resources:
  - name: src
    type: git
    icon: github
    source:
      uri: https://github.com/electrocucaracha/k8s-HorizontalPodAutoscaler-demo.git
      branch: master

groups:
  - name: develop
    jobs:
      - linting
      - unit-tests

jobs:
  - name: linting
    public: true
    serial: true
    plan:
      - get: src
        trigger: true
      - in_parallel:
          - task: tox
            file: src/build/ci/linter-task.yml
            params:
              RELENG_LINTER_TOOL: tox
          - task: shellcheck
            file: src/build/ci/linter-task.yml
            params:
              RELENG_LINTER_TOOL: shellcheck
          - task: hadolint
            file: src/build/ci/linter-task.yml
            params:
              RELENG_LINTER_TOOL: hadolint
  - name: unit-tests
    public: true
    serial: true
    plan:
      - get: src
        trigger: true
      - task: go-test
        file: src/build/ci/go-test-task.yml
