---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c)
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

resources:
  - name: src
    type: git
    icon: github
    source:
      uri: https://github.com/electrocucaracha/releng.git
      branch: master

jobs:
  - name: linting
    public: true
    plan:
      - get: src
        trigger: true
      - task: tox
        file: src/build/ci/tox-task.yml
      - task: shellcheck
        file: src/build/ci/shellcheck-task.yml
