title = "releng gitleaks config"

[extend]
useDefault = true

[[allowlists]]
id = "allow-env-var-creds"
description = "Allow curl basic auth with env var credentials"
regexTarget = "line"
regexes = ['''-u "\$\{.*\}" -p "\$\{.*\}"''']
