---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c)
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
resources:
  - name: src
    type: git
    icon: github
    source:
      uri: https://github.com/electrocucaracha/linter.git
      branch: master
groups:
  - name: unit-test
    jobs:
      - linting
  - name: integration-test
    jobs:
      - build-image-test
jobs:
  - name: linting
    serial: true
    plan:
      - get: src
        trigger: true
      - in_parallel:
          - task: tox
            file: src/build/ci/linter-task.yml
            params:
              RELENG_LINTER_TOOL: tox
          - task: shellcheck
            file: src/build/ci/linter-task.yml
            params:
              RELENG_LINTER_TOOL: shellcheck
          - task: hadolint
            file: src/build/ci/linter-task.yml
            params:
              RELENG_LINTER_TOOL: hadolint
  - name: build-image-test
    serial: true
    plan:
      - get: src
        trigger: true
      - task: build
        privileged: true
        file: src/build/ci/docker-task.yml
        params:
          MAKE_ACTION: build
