---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c)
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: vind-run
spec:
  pipelineRef:
    name: vind
  podTemplate:
  serviceAccountName: 'default'
  resources:
    - name: src
      resourceRef:
        name: vind-git
