---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2025
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
name: Create and publish Docker image
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    tags:
      - "v*"
  pull_request:
    branches:
      - "master"
jobs:
  changes:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      changed_services: ${{ steps.services.outputs.changed_services }}
    if: >-
      ( github.event_name == 'pull_request_review' && github.event.review.state == 'approved' ) || github.event_name != 'pull_request_review'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          persist-credentials: false
      - id: changed-files
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # 47.0.5
        with:
          json: true
          escape_json: false
          files: |
            ./mirror/ntpd/Dockerfile
            ./mirror/apt-mirror/Dockerfile
            ./mirror/devpi/Dockerfile
            ./mirror/nginx/Dockerfile
      - name: Determine changed services
        id: services
        env:
          ALL_MODIFIED_FILES: ${{ steps.changed-files.outputs.all_modified_files }}
        run: |
          changed_services=$(jq -c -n --argjson files "${ALL_MODIFIED_FILES}" '$files | map(sub("^mirror/";"") | sub("/Dockerfile$";"")) | map({service: .})')
          echo "changed_services=$changed_services" >> "$GITHUB_OUTPUT"
  build:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    if: needs.changes.outputs.changed_services != '[]'
    needs: changes
    strategy:
      matrix:
        include: ${{ fromJson(needs.changes.outputs.changed_services) }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          persist-credentials: false
      - name: Log in to the Container registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # 4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # 6.0.0
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.service }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # 7.0.0
        with:
          context: ./mirror/${{ matrix.service }}/
          file: ./mirror/${{ matrix.service }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository }}/${{ matrix.service }}:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # 4.1.0
        with:
          subject-name: ghcr.io/${{ github.repository }}/${{ matrix.service }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
