---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2025
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
name: Create and publish Docker image
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    tags:
      - "v*"
  pull_request:
    branches:
      - "master"
jobs:
  changes:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      changed_services: ${{ steps.services.outputs.changed_services }}
    if: >-
      ( github.event_name == 'pull_request_review' && github.event.review.state == 'approved' ) || github.event_name != 'pull_request_review'
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
        with:
          persist-credentials: false
      - id: changed-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # 47.0.0
        with:
          json: true
          files: |
            ./mirror/ntpd/Dockerfile
            ./mirror/apt-mirror/Dockerfile
            ./mirror/devpi/Dockerfile
            ./mirror/nginx/Dockerfile
      - name: Determine changed services
        id: services
        run: |
          changed_services=$(jq -c -n --argjson files $(echo ${{ steps.changed-files.outputs.all_modified_files }}) '$files | map(sub("^mirror/";"") | sub("/Dockerfile$";"")) | map({service: .})')
          echo "changed_services=$changed_services" >> $GITHUB_OUTPUT
  build:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    if: needs.changes.outputs.changed_services != '[]'
    needs: changes
    strategy:
      matrix:
        include: ${{ fromJson(needs.changes.outputs.changed_services) }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
        with:
          persist-credentials: false
      - name: Log in to the Container registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # 3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # 5.8.0
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.service }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # 6.18.0
        with:
          context: ./mirror/${{ matrix.service }}/
          file: ./mirror/${{ matrix.service }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository }}/${{ matrix.service }}:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # 3.0.0
        with:
          subject-name: ghcr.io/${{ github.repository }}/${{ matrix.service }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
