---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check Lastest Distros
# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: '0 0 1 * *'
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  check-versions:
    permissions:
      contents: write  # for technote-space/create-pr-action to push code
      pull-requests: write  # for technote-space/create-pr-action to create a PR
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4.2.1
      - uses: actions/cache@v4.1.1
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-
      - uses: technote-space/create-pr-action@v2.1.4
        with:
          EXECUTE_COMMANDS: |
            ./update_distros.sh
          COMMIT_MESSAGE: 'Upgrade distro list versions'
          COMMIT_NAME: 'electrocucaracha bot'
          PR_BRANCH_NAME: "versions-update-${PR_ID}"
          PR_TITLE: 'chore: update distro versions'
