---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check Mirror Bare-Metal deployment
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'master'

jobs:
  check-mirror:
    runs-on: ubuntu-18.04
    env:
      RELENG_MIRROR_FILE: mirror_releng.list
    steps:
      - uses: actions/checkout@v2
      - name: Setup the VM folders
        run: |
          ./pre-install.sh "sdc" "/var/local/packages"
          ./pre-install.sh "sdd" "/var/local/images"
          ./pre-install.sh "sdf" "/var/local/pypi_packages"
      - name: Install dependencies
        run: cd mirror; ./install.sh
      - name: Deploy docker compose services
        run: cd mirror; ./deploy.sh
      - name: Pull KinD docker images
        run: cd mirror; ./setup_k8s.sh
      - name: Retrieve images hosted in private registry
        run: curl -s -X GET http://localhost:5000/v2/_catalog
