---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check CI
# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  check-ci-baremetal:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ci: [concourse, tekton]
    env:
      PKG_KUBECTL_VERSION: v1.18.8
      RELENG_CI_TYPE: ${{ matrix.ci }}
    steps:
      - uses: actions/checkout@v2
      - name: Provision a Kubernetes cluster
        run: cd ci; ./provision_kind_cluster.sh
      - name: Deploy CI services
        run: cd ci/${RELENG_CI_TYPE}; ./deploy.sh
      - name: Get nodes information
        run: kubectl describe nodes
  check-mirror-baremetal:
    runs-on: ubuntu-18.04
    env:
      RELENG_MIRROR_FILE: mirror_releng.list
    steps:
      - uses: actions/checkout@v2
      - name: Setup the VM folders
        run: |
          ./pre-install.sh "sdc" "/var/local/packages"
          ./pre-install.sh "sdd" "/var/local/images"
          ./pre-install.sh "sdf" "/var/local/pypi_packages"
      - name: Install dependencies
        run: cd mirror; ./install.sh
      - name: Deploy docker compose services
        run: cd mirror; ./deploy.sh
      - name: Pull KinD docker images
        run: cd mirror; ./setup_k8s.sh
      - name: Retrieve images hosted in private registry
        run: curl -s -X GET http://localhost:5000/v2/_catalog
  check-e2e:
    runs-on: macos-10.15
    env:
      VAGRANT_NAME: ${{ matrix.name }}
      VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1
      VAGRANT_EXPERIMENTAL: disks
      CPUS: 2
      MEMORY: 12288
    steps:
      - uses: actions/checkout@v2
      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-
      - name: Install GNU tools
        run: brew install proctools iproute2mac
      - name: Replace shorten links
        run: find . -type f -iname "*sh" -exec sed -i '.bak' 's|http://bit.ly/install_pkg|https://raw.githubusercontent.com/electrocucaracha/pkg-mgr_scripts/master/install.sh|g' {} \;
      - name: Run mirror
        run: vagrant up
      - name: Create CI instance
        run: vagrant up ci
      - name: Destroy CI instance
        if: ${{ always() }}
        run: vagrant destroy -f ci
      - name: Create cloud instance
        run: vagrant up cloud
      - name: Destroy Cloud instance
        if: ${{ always() }}
        run: vagrant destroy -f cloud
