---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check Mirror
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - 'pre-install.sh'
      - 'mirror/*'
  pull_request_review:
    types:
      - submitted

jobs:
  check-mirror-baremetal:
    name: Check Mirror deployment on Ubuntu Bionic Virtual Environment
    if: >-
      (
        github.event_name == 'pull_request_review' &&
        github.event.review.state == 'approved'
      ) ||
      github.event_name != 'pull_request_review'
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        service: [k8s, devpi, kolla]
    env:
      RELENG_KOLLA_BUILD: "true"
      RELENG_DEBUG: "true"
    steps:
      - uses: actions/checkout@v3
      - name: Setup the VM folders
        run: |
          ./pre-install.sh "sdc" "/var/local/packages"
          ./pre-install.sh "sdd" "/var/local/images"
          ./pre-install.sh "sdf" "/var/local/pypi_packages"
      - name: Install dependencies
        run: cd mirror; ./install.sh
      - name: Deploy docker compose services
        env:
          MIRROR_FILENAME: mirror_releng.list
        run: cd mirror; ./deploy.sh
      - name: Deploy service
        env:
          SERVICE: ${{ matrix.service }}
          RELENG_FOLDER: "../"
          RELENG_KOLLA_BUILD: "true"
        run: cd mirror; "./setup_$SERVICE.sh"
      - name: Retrieve images hosted in private registry
        run: curl -s -X GET http://localhost:5000/v2/_catalog
      - name: Check logs
        if: ${{ failure() }}
        run: docker-compose -f mirror/docker-compose.yml logs
