---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check CI
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - '*install.sh'
      - 'ci/*'
  pull_request_review:
    types:
      - submitted
    paths:
      - '*install.sh'
      - 'ci/*'

jobs:
  check-ci-baremetal:
    name: Check CI deployment on Ubuntu Bionic Virtual Environment
    if: >-
      (
        github.event_name == 'pull_request_review' &&
        github.event.review.state == 'approved'
      ) ||
      github.event_name != 'pull_request_review'
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - ci: concourse
            k8s: kind
          - ci: tekton
            k8s: krd
    env:
      RELENG_DEBUG: "true"
    steps:
      - uses: actions/checkout@v2
      - name: Provision a Kubernetes cluster
        env:
          RELENG_K8S_TYPE: ${{ matrix.k8s }}
        run: cd ci; "./provision_${RELENG_K8S_TYPE}_cluster.sh"
      - name: Deploy CI services
        env:
          RELENG_CI_TYPE: ${{ matrix.ci }}
        run: cd "ci/${RELENG_CI_TYPE}"; ./deploy.sh
      - name: Get nodes information
        if: ${{ failure() }}
        run: |
          kubectl get events -A --sort-by=".metadata.managedFields[0].time"
          kubectl get all -A -o wide
          kubectl describe nodes
